# Generated by Django 2.2.3 on 2019-07-15 01:05

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('code', models.CharField(default='', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_no', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('is_company', models.BooleanField()),
                ('price_type', models.CharField(choices=[('R', 'Retail'), ('W', 'Wholesale'), ('D', 'Dealer'), ('S', 'Special')], default='R', max_length=2)),
                ('unit_number', models.CharField(blank=True, max_length=50, verbose_name='House/Appt No')),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('vat_registration_number', models.IntegerField(blank=True, default=0)),
                ('business_registration_number', models.CharField(blank=True, max_length=9)),
                ('discount_percent', models.FloatField(blank=True, default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 7, 15, 1, 5, 3, 891953, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 7, 15, 1, 5, 3, 892029, tzinfo=utc))),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('namefirst', models.CharField(max_length=16, verbose_name='First name')),
                ('namelast', models.CharField(max_length=16, verbose_name='Last name')),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(max_length=200)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('state', models.CharField(max_length=250)),
                ('money', models.IntegerField()),
                ('postcode', models.CharField(max_length=250)),
                ('date_of_birth', models.DateField(default=None, verbose_name='Date of Birth')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('bills', 'Bills'), ('Payments', 'payments'), ('pettycash', 'Pettycash'), ('other', 'Other')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('Product', models.CharField(default='', max_length=100, unique=True)),
                ('Quantity', models.IntegerField()),
                ('supplier', models.CharField(default='', max_length=100, unique=True)),
                ('Date_recieved', models.DateTimeField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('tonality', models.CharField(blank=True, max_length=5)),
                ('caliber', models.CharField(blank=True, max_length=5)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('retail_unit', models.CharField(choices=[('SF', 'Square Feet'), ('SM', 'Square Metre'), ('U', 'Unit')], default='U', max_length=2)),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('wholesale_unit', models.CharField(choices=[('SF', 'Square Feet'), ('SM', 'Square Metre'), ('U', 'Unit')], default='U', max_length=2)),
                ('dealer_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('dealer_unit', models.CharField(choices=[('SF', 'Square Feet'), ('SM', 'Square Metre'), ('U', 'Unit')], default='U', max_length=2)),
                ('special_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('special_unit', models.CharField(choices=[('SF', 'Square Feet'), ('SM', 'Square Metre'), ('U', 'Unit')], default='U', max_length=2)),
                ('pieces_per_box', models.IntegerField(blank=True, default=0, null=True)),
                ('exempt_flag', models.BooleanField(default=False)),
                ('nonstock_flag', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountingApp.Category')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountingApp.Country')),
            ],
        ),
        migrations.CreateModel(
            name='sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.IntegerField()),
                ('date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('requisition_number', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 7, 15, 1, 5, 3, 902275, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 7, 15, 1, 5, 3, 902365, tzinfo=utc))),
                ('Amount', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountingApp.Customer')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountingApp.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.IntegerField()),
                ('date', models.DateField()),
                ('supplier', models.CharField(max_length=233)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('date_of_purchase', models.DateTimeField(default=datetime.datetime(2019, 7, 15, 1, 5, 3, 902953, tzinfo=utc))),
                ('Amount', models.IntegerField()),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountingApp.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('basic_pay', models.IntegerField(default=0)),
                ('benefits', models.IntegerField(default=0)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll', to='accountingApp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
