# Generated by Django 2.2.3 on 2019-07-15 01:46

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accountingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='purpose',
            field=models.CharField(default=django.utils.timezone.now, max_length=240),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 1, 45, 51, 757092, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 1, 45, 51, 757174, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date_of_purchase',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 1, 45, 51, 768081, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 1, 45, 51, 767599, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 1, 45, 51, 767678, tzinfo=utc)),
        ),
    ]
