# Generated by Django 2.2.3 on 2019-07-27 12:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accountingApp', '0003_auto_20190715_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 27, 12, 29, 22, 930010, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 27, 12, 29, 22, 930093, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date_of_purchase',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 27, 12, 29, 22, 941095, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 27, 12, 29, 22, 940622, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 27, 12, 29, 22, 940709, tzinfo=utc)),
        ),
    ]
