# Generated by Django 2.2.3 on 2019-07-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingApp', '0004_auto_20190727_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='invoice_no',
            new_name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date_of_purchase',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
