# Generated by Django 2.2.5 on 2019-09-16 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accountingApp', '0005_auto_20190729_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sold_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
